name = "medium-app"
compatibility_date = "2023-12-01"

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYjEwMWEzYWUtODkzNi00YTMxLTkzNzUtNWU3Y2Q1Mzc5OTllIiwidGVuYW50X2lkIjoiNmVhY2MyYzA5OTg5YTJlMDlmZTI5MWRkNmVmNjc2ZDI0NDlhZWIxNjQ3ZTViOTRjOTVkMzExN2NiN2EyMTU3YiIsImludGVybmFsX3NlY3JldCI6IjNjNmJkNWM1LWQ5ZDctNGVkMi04MWQzLWFmMGI4NjlkZmQyMSJ9.d62x9Cjb2MgyFHkmxw_wuJQvwlImG5L9s6mPkur7Or0"
SECRET_KEY = "secret"
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
